import { Link } from "react-router-dom";

// ============================================================
// TÜM SİTE METİNLERİ — Türkçe (tr) ve İngilizce (en).
// Bir metni değiştirmek için iki dilde de ilgili satırı düzenleyin.
// ============================================================

export const METIN = {
  /* ================================================================ TÜRKÇE */
  tr: {
    nav: {
      linkler: [
        { to: "/hakkimizda", ad: "Hakkımızda" },
        { to: "/etkinlikler", ad: "Etkinlikler" },
        { to: "/kulupler", ad: "Kulüpler" },
        { to: "/faydali-siteler", ad: "Faydalı Siteler" },
        { to: "/katil", ad: "Katıl" },
      ],
      discordAria: "Discord sunucumuza katıl",
      menuAria: "Menüyü aç/kapat",
      temaAcik: "Açık temaya geç",
      temaKoyu: "Koyu temaya geç",
      skip: "İçeriğe atla",
      mnavDiscord: "Discord'a Katıl",
      mnavKoordinat: "36°–42°K · 26°–45°D · TÜRKİYE",
      markaAria: "GeoGuessrTürkiye ana sayfa",
    },
    footer: {
      aciklama: "Türkiye'nin ilk kurulan ve en büyük GeoGuessr topluluğu. Bağımsız bir topluluk oluşumudur; GeoGuessr AB ile resmî bir bağı yoktur.",
      sayfalar: "Sayfalar",
      anaSayfa: "Ana Sayfa",
      topluluk: "Topluluk",
      iletisim: "İletişim",
      sss: "Sık Sorulan Sorular",
      telif: "Tüm hakları topluluğundur.",
      koordinat: "39.93°K · 32.86°D",
      sevgi: "Türkiye'den sevgilerle",
      mailYok: "Mail adresi henüz hazır değil",
    },
    varsayilanAciklama: "GeoGuessr Türkiye; ilk kurulan ve en büyük Türk GeoGuessr topluluğudur. Turnuvaları, kulüpleri ve Türkçe rehberleriyle Türkiye'nin GeoGuessr oyuncularını aynı haritada buluşturan bağımsız topluluk. Katılım açık ve ücretsiz.",
    home: {
      eyebrow: "Türkiye'nin GeoGuessr Topluluğu",
      h1: [
        { w: "Dünyayı" },
        { w: "avucunun içi", accent: true },
        { w: "gibi" },
        { w: "bilen" },
        { w: "topluluk." },
      ],
      tanitim: "GeoGuessrTürkiye; ilk kurulan ve en büyük Türk GeoGuessr topluluğudur. Turnuvaları, ligleri ve rehberleriyle Türkiye'nin GeoGuessr oyuncularını aynı haritada buluşturur.",
      ctaDiscord: "Discord'a Katıl",
      ctaTani: "Topluluğu Tanı",
      meta: [
        ["KONUM", "Türkiye"],
        ["PLATFORM", "Discord + Web"],
        ["ÜYELİK", "Açık ve ücretsiz"],
      ],
      canli: "Her saniye binlerce tahmin yapılıyor",
      manifesto1a: "Bir sokak tabelasından, bir ağaca, kameranın jenerasyonundan, Google çekimlerinin inceliklerinin peşinde olan ",
      manifesto1em: "her geçen gün büyüyen ve gelişen",
      manifesto1b: " bir topluluğuz.",
      manifesto2: "İster daha ilk tahminini yapıyor ol, ister dünya sıralamasında yarışıyor ol: bu çatının altında herkese yer var. Aramıza katılan herkesi ilk günkü heyecanla karşılıyoruz.",
      faktalar: [
        { n: 81, say: true, l: "İlden Oyuncu" },
        { n: 1300, say: true, ek: "+", l: "Üye" },
        { n: "7/24", l: "Aktif Topluluk" },
        { n: "∞", l: "Konum Sayısı" },
      ],
      neEyebrow: "Ne Yapıyoruz",
      neH2: "Dört başlıkta GeoGuessrTürkiye",
      neler: [
        { no: "01", baslik: "Turnuvalar & Ligler", to: "/etkinlikler", p: "Kupalardan lige: her seviyeden oyuncunun rekabet edebileceği etkinlikler düzenliyoruz." },
        { no: "02", baslik: "Rehberler & Meta", to: "/faydali-siteler", p: "Ülke tanıma, plaka ve direksiyon ipuçları, kamera nesilleri, bollard'lar… Türkçe kaynak eksikliğini biz kapatıyoruz." },
        { no: "03", baslik: "Kulüpler", to: "/kulupler", p: "GeoGuessr üzerindeki resmî kulüplerimiz: katıl, rozetini tak, kulüp yarışmalarında Türkiye'yi temsil et." },
        { no: "04", baslik: "Temsil & İş Birlikleri", to: "/hakkimizda", p: "Uluslararası etkinliklerde Türkiye'yi temsil ediyor, diğer ülke toplulukları ile dostluk maçları düzenliyoruz." },
      ],
      takvimEyebrow: "Takvim",
      takvimH2: "Etkinlik takvimi",
      takvimBtn: "Etkinlikler",
      programTag: "Program: Hazırlanıyor",
      programH3: "Düzenli haftalık program çok yakında.",
      programP: "Takvim netleşene kadar tüm etkinlikler Discord sunucumuzda duyuruluyor. Geçmiş turnuvalarımıza Etkinlikler sayfasından göz atabilirsin.",
      programBtn1: "Duyuruları Takip Et",
      programBtn2: "Geçmiş Turnuvalar",
      sozlukEyebrow: "Sözlük",
      sozlukH2: "Üç mod, üç ayrı disiplin",
      sozlukLead: "GeoGuessr'da nasıl oynadığın, ne kadar bildiğin kadar önemli. Etkinliklerimizde üç ana mod kullanıyoruz.",
      modlar: [
        { abbr: "MOD 01", ad: "Moving", p: "Serbest keşif. Yollarda ilerle, tabela topla, kavşakları takip et. Sabır ve yol bilgisi kazandırır.", kurallar: [["ok", "HAREKET", "SERBEST"], ["ok", "YAKINLAŞTIRMA", "SERBEST"], ["ok", "ETRAFA BAKMA", "SERBEST"]] },
        { abbr: "MOD 02", ad: "No Move", p: "Olduğun yerden analiz. Bitki örtüsü, mimari, güneşin yönü… Tek karede ne kadar detay görebilirsin?", kurallar: [["no", "HAREKET", "KAPALI"], ["ok", "YAKINLAŞTIRMA", "SERBEST"], ["ok", "ETRAFA BAKMA", "SERBEST"]] },
        { abbr: "MOD 03", ad: "NMPZ", p: "Saf içgüdü. Ne hareket, ne zoom, ne dönüş. Tek bakışta ülkeyi okumak, ustalığın gerçek ölçüsüdür.", kurallar: [["no", "HAREKET", "KAPALI"], ["no", "YAKINLAŞTIRMA", "KAPALI"], ["no", "ETRAFA BAKMA", "KAPALI"]] },
      ],
      ctaEyebrow: "Aramıza Katıl",
      ctaH2: "Sıradaki turda yerini al.",
      ctaNot: "Not: Discord'a Türkiye'den erişimde zaman zaman sorun yaşanabiliyor. Güncel duyurular ve etkinlik takvimi her zaman bu sitede yayınlanır.",
      ctaBtn1: "Discord Sunucusu",
      ctaBtn2: "Katılım Rehberi",
    },
    hakkimizda: {
      title: "Hakkımızda",
      desc: "GeoGuessrTürkiye'nin hikâyesi: Türkiye'deki GeoGuessr oyuncularını bir araya getiren bağımsız topluluğun kuruluşu, ilkeleri ve ekibi.",
      eyebrow: "Hakkımızda",
      h1: "GeoGuessr Türkiye Topluluğu.",
      lead: "GeoGuessrTürkiye; ilk kurulan ve en büyük Türk GeoGuessr topluluğu, aynı zamanda dünyanın en büyük GeoGuessr topluluklarından biridir. Türkiye'deki oyuncuları bir araya getirmek için oyuncular tarafından kurulmuş bağımsız bir topluluktur; bu site, topluluğun herkese açık yüzü ve resmî duyuru kanalıdır.",
      koordinat: "39.93°K · 32.86°D · ANKARA",
      hikayeEyebrow: "Hikâyemiz",
      hikayeH2: "Birkaç oyuncudan bir topluluğa",
      hikaye: [
        "Her şey, GeoGuessr oynayan birkaç Türk oyuncunun birbirini bulmasıyla başladı. Sokak görüntülerinden ülke okumak eğlenceli bir merakken; skorları karşılaştırmak, ipuçlarını paylaşmak ve birlikte oynamak için bir buluşma noktasına ihtiyaç doğdu. Discord sunucumuz böyle kuruldu.",
        "Zamanla merak, düzene dönüştü: turnuvalar, Türkçe rehberler ve topluluğun kendi elleriyle hazırladığı Türkiye haritaları… Bugün ilk kurulan ve en büyük Türk GeoGuessr topluluğu olarak her seviyeden oyuncunun aynı lobide buluştuğu, dünyanın en büyük GeoGuessr topluluklarından biriyiz.",
        "Bu web sitesi, topluluğa erişimin her koşulda sürmesi için açıldı. Duyurularımız, etkinlik takvimimiz ve rehberlerimiz artık herkesin ulaşabileceği bu adreste yaşıyor.",
      ],
      ilkeEyebrow: "İlkelerimiz",
      ilkeH2: "Bizi bir arada tutan dört ilke",
      ilkeler: [
        { no: "01", ad: "Merak", p: "Bir tabelanın dilinden bir dağın siluetine, dünyayı tanımaya duyulan doymaz istek. Öğrenmeyi oyunun kendisi sayarız." },
        { no: "02", ad: "Rekabet", p: "Skor tablosu ciddiye alınır; ama en keskin rekabet bile centilmenliğin önüne geçmez. Adil oyun, tartışılmaz kuraldır." },
        { no: "03", ad: "Paylaşım", p: "Meta bilgisi saklanmaz, öğretilir. Yeni başlayan herkes, bugün usta olanların bir zamanlar sorduğu soruları sorabilmelidir." },
        { no: "04", ad: "Saygı", p: "Farklı şehirlerden, farklı yaşlardan, farklı seviyelerden oyuncular tek çatı altındayız. Burada herkesin yeri var." },
      ],
      yolEyebrow: "Yolculuğumuz",
      yolH2: "Kilometre taşları",
      yolculuk: [
        { tarih: "31.12.2022", etiket: "Kuruluş", ad: "İlk buluşma", p: "Bir avuç oyuncu, Türkçe konuşulan bir GeoGuessr sunucusu hayaliyle Discord'da bir araya geldi ve GeoGuessrTürkiye kuruldu." },
        { tarih: "2023", etiket: "Turnuvalar", ad: "Turnuvalar başlıyor", p: "İlk GeoGuessr Türkiye turnuvaları düzenlendi. Kazananlar kadar, formatın kendisi de topluluğun geleneği hâline geldi." },
        { tarih: "Büyüme", etiket: "Rehberler", ad: "Rehberler ve haritalar", p: "Türkçe meta rehberleri yayımlandı; topluluk üyelerinin hazırladığı dengeli Türkiye haritaları oyuncularla buluştu." },
        { tarih: "2026", etiket: "Yayında", ad: "geoturkiye.community açılıyor", p: "Topluluğun kalıcı ve herkese açık adresi yayında. Duyurular, takvim ve rehberler artık tek çatı altında." },
      ],
      ekipEyebrow: "Ekip",
      ekipH2: "Topluluğu kimler yürütüyor?",
      ekipLead: "GeoGuessr Türkiye tamamen gönüllü emeğiyle büyümekte ve yönetilmektedir.",
      /* GÜNCELLE: YouTube ve Instagram linklerini ekleyin ("#" yerine) */
      ekipKisiler: [
        { ad: "Oğuzhan Sarıgöl", rol: "Moderatör", img: "/ekip/oguzhansarigol.png", youtube: "https://www.youtube.com/@oguzhansarigol", instagram: "https://www.instagram.com/oguzhansarigol_" },
        { ad: "Ahmet Yusuf Kartal", rol: "Moderatör", img: "/ekip/ahmetyusufkartal.png", youtube: "https://www.youtube.com/@ayusufkartal", instagram: "https://www.instagram.com/a.yusufkartal" },
        { ad: "Fez", rol: "Moderatör", img: "/ekip/fez.png", youtube: "https://www.youtube.com/@regularcinemapod", kick: "https://kick.com/butfezz" },
      ],
      ekipCokluBaslik: "Gönüllü Yöneticiler",
      ekipCokluP: "Ve daha birçok gönüllü yönetici; sunucuyu her gün birlikte ayakta tutuyorlar.",
      ctaEyebrow: "Sen de Katıl",
      ctaH2: "Hikâyenin devamını birlikte yazalım.",
      ctaBtn1: "Discord Sunucusu",
      ctaBtn2: "Katılım Rehberi",
    },
    etkinlikler: {
      title: "Etkinlikler",
      desc: "GeoGuessrTürkiye turnuvaları: geçmiş turnuvalar ve yeni sezon hazırlıkları. Duyurular Discord'da.",
      eyebrow: "Etkinlikler",
      h1: "Yeni turnuvalar yolda.",
      lead: "Şu anda aktif bir turnuvamız yok. Bugüne dek üç GeoGuessr Türkiye turnuvası ve bir offline turnuva düzenledik; yenileri için hazırlıklar sürüyor.",
      koordinat: "DURUM: YAPIM AŞAMASINDA",
      insaTag: "Sayfa Yapım Aşamasında",
      insaH3: "Yeni turnuva sezonu hazırlanıyor.",
      insaP: "Format ve takvim netleştiğinde bu sayfa güncellenecek. O güne kadar tüm duyurular Discord sunucumuzda yayınlanıyor.",
      insaBtn: "Duyuruları Takip Et",
      turnuvaEyebrow: "Başvuru",
      turnuvaH2: "Açık turnuvalar",
      tKontenjan: "Kontenjan",
      tBasvurBtn: "Başvur",
      tVazgec: "Vazgeç",
      tDolu: "Kontenjan doldu",
      tDiscordNot: "Duyurular Discord sunucumuzdaki turnuva kanalından yapılır — başvurudan sonra takipte kal.",
      fDiscord: "Discord kullanıcı adı",
      fDiscordPh: "örn. geoturkiye",
      fProfil: "GeoGuessr profil linki",
      fProfilPh: "https://www.geoguessr.com/user/…",
      fAdSoyad: "Ad Soyad (opsiyonel)",
      fGonder: "Başvuruyu Gönder",
      fGonderiliyor: "Gönderiliyor…",
      fBasari: "Başvurun alındı! Sonuçlar ve duyurular Discord'daki turnuva kanalından paylaşılacak.",
      fHataTekrar: "Bu Discord adıyla bu turnuvaya zaten başvuru yapılmış.",
      fHataGenel: "Başvuru gönderilemedi. Turnuva kapanmış veya kontenjan dolmuş olabilir — Discord'dan bize ulaş.",
      fZorunlu: "Lütfen zorunlu alanları doldur.",
      arsivEyebrow: "Arşiv",
      arsivH2: "Geçmiş turnuvalar",
      tabloBasliklar: ["#", "Turnuva", "Tarih", "Format"],
      /* GÜNCELLE: 3. turnuvanın ve offline turnuvanın tarihlerini ekleyin */
      gecmis: [
        { no: "01", ad: "GeoGuessr Türkiye Turnuvası 1", tarih: "05.08.2023", tur: "Çevrim içi" },
        { no: "02", ad: "GeoGuessr Türkiye Turnuvası 2", tarih: "02.09.2023", tur: "Çevrim içi" },
        { no: "03", ad: "GeoGuessr Türkiye Turnuvası 3", tarih: "Tarih eklenecek", tur: "Çevrim içi" },
        { no: "04", ad: "Offline Turnuva", tarih: "Tarih eklenecek", tur: "Yüz yüze" },
      ],
      ctaEyebrow: "Hazır mısın?",
      ctaH2: "Bir sonraki turnuvayı kaçırma.",
      ctaBtn1: "Discord Sunucusu",
      ctaBtn2: "Katılım Rehberi",
    },
    kulupler: {
      title: "Kulüpler",
      desc: "GeoGuessrTürkiye'nin GeoGuessr kulüpleri: ana kulüp ve kardeş kulüplere katıl, rozetini tak, Türkiye'yi temsil et.",
      eyebrow: "Kulüpler",
      h1: "Kulüplerimiz.",
      lead: "GeoGuessr üzerindeki resmî kulüplerimiz. Katıl, rozetini tak, topluluğun bir parçası ol. Kontenjanlar dolu olabilir — yer yoksa aşağıdaki formdan başvurunu bırak, yer açılınca Discord'dan haber veririz.",
      koordinat: "3 KULÜP · GEOGUESSR ÜZERİNDE",
      /* GÜNCELLE: Kulüp adlarını ve açıklamalarını dilediğiniz gibi düzenleyin */
      liste: [
        { ad: "GeoGuessr Türkiye", tag: "Ana Kulüp", url: "https://www.geoguessr.com/clubs/4d3821c4-6e74-4c41-a5ed-6a12ca38970e", p: "Topluluğun ana kulübü. Rozet ve topluluk burada; kontenjan doluysa aşağıdan başvur." },
        { ad: "GeoGuessr Türkiye 2", tag: "Kulüp 02", url: "https://www.geoguessr.com/clubs/8258105f-5397-400e-983c-29103330ecc7", p: "Ana kulüp dolduğunda ikinci durak. Aynı topluluk, aynı heyecan." },
        { ad: "GeoGuessr Türkiye 3", tag: "Kulüp 03", url: "https://www.geoguessr.com/clubs/ae825f43-3377-4a54-9141-3ac4afd624c0", p: "Üçüncü kulübümüz. Yeni katılanlar için her zaman bir yer var." },
      ],
      katilBtn: "Kulübe Katıl",
      not: "Kulüplere katılmak için bir GeoGuessr hesabı gerekir. Kontenjanlar sınırlıdır; ana kulüp doluysa sıradaki kulüpten devam edebilirsin.",
      basvurBtn: "Kulübe Başvur",
      formEyebrow: "Başvuru",
      formH2: "Kulüp başvurusu",
      formLead: "Kulüpler dolu olduğunda buradan başvurabilirsin; yer açıldıkça Discord üzerinden dönüş yapılır.",
      fKulup: "Kulüp",
      fDiscord: "Discord kullanıcı adı",
      fDiscordPh: "örn. geoturkiye",
      fProfil: "GeoGuessr profil linki",
      fProfilPh: "https://www.geoguessr.com/user/…",
      fAdSoyad: "Ad Soyad (opsiyonel)",
      fGonder: "Başvuruyu Gönder",
      fGonderiliyor: "Gönderiliyor…",
      fBasari: "Başvurun alındı! Yer açıldığında Discord üzerinden sana ulaşacağız.",
      fHataTekrar: "Bu Discord adıyla bu kulübe zaten başvuru yapılmış.",
      fHataGenel: "Başvuru gönderilemedi. Lütfen daha sonra tekrar dene veya Discord'dan bize ulaş.",
      fZorunlu: "Lütfen zorunlu alanları doldur.",
    },
    faydali: {
      title: "Faydalı Siteler",
      desc: "GeoGuessr oyuncusunun araç çantası: Plonk It, GeoHints, Learnable Meta ve daha fazlası. Topluluğun sık kullandığı güvenilir kaynaklar.",
      eyebrow: "Faydalı Siteler",
      h1: "Harita başındakinin araç çantası.",
      lead: "Meta öğrenmekten harita yapmaya: topluluğun sık kullandığı, güvenilir dış kaynaklar. Hepsi tek listede.",
      koordinatSon: "KAYNAK · DIŞ BAĞLANTI",
      siteler: [
        { no: "01", ad: "GeoGuessr", url: "https://www.geoguessr.com", host: "geoguessr.com", p: "Oyunun resmî adresi. Hesap açmak ve oynamaya başlamak için ilk durak." },
        { no: "02", ad: "Plonk It", url: "https://www.plonkit.net", host: "plonkit.net", p: "Ülke ülke hazırlanmış, dünyanın en kapsamlı meta rehberi. Ciddi gelişmek isteyenin başucu kaynağı." },
        { no: "03", ad: "Learnable Meta", url: "https://learnablemeta.com", host: "learnablemeta.com", p: "Ülke metalarını küçük dersler hâlinde öğreten, quizlerle pekiştiren interaktif çalışma platformu." },
        { no: "04", ad: "MagnusGeo Rehberi (Türkçe)", url: "https://geo.magnusmagi.com/tr", host: "geo.magnusmagi.com/tr", p: "Türkçe hazırlanmış meta rehberi; ülke ipuçlarını kendi dilinde öğrenmek için birebir." },
        { no: "05", ad: "GeoHints", url: "https://geohints.com", host: "geohints.com", p: "Direkler, bollard'lar, plakalar, alan kodları… Ülkeleri görsel ipuçlarıyla yan yana karşılaştırır." },
        { no: "06", ad: "GeoTips", url: "https://geotips.net", host: "geotips.net", p: "Bölge bölge kısa notlar ve pratik meta ipuçları; hızlı tekrar için ideal." },
        { no: "07", ad: "MagnusGeo", url: "https://magnusgeo.magnusmagi.com", host: "magnusgeo.magnusmagi.com", p: "Liderlik tabloları ve oyun profillerine dahil analizler." },
        { no: "08", ad: "Seterra", url: "https://www.seterra.com", host: "seterra.com", p: "Başkentler, bayraklar, iller… Coğrafya bilgisini oyunlaştırılmış alıştırmalarla pekiştirir." },
        { no: "09", ad: "Map Making App", url: "https://map-making.app", host: "map-making.app", p: "Kendi GeoGuessr haritanı hazırlamak için topluluğun standart aracı." },
        { no: "10", ad: "r/geoguessr", url: "https://www.reddit.com/r/geoguessr/", host: "reddit.com/r/geoguessr", p: "Uluslararası GeoGuessr topluluğunun forumu; haberler, tartışmalar ve turnuva duyuruları." },
      ],
      not: "Bağlantılar üçüncü taraf sitelere gider; içeriklerin çoğu İngilizcedir. Türkçe rehberlerimiz için Discord sunucumuzdaki rehber kanallarına göz atabilirsin.",
      ctaEyebrow: "Öneri",
      ctaH2: "Listeye girmesi gereken bir site mi var?",
      ctaBtn1: "Discord'da Öner",
      ctaBtn2: "Katılım Rehberi",
    },
    katil: {
      title: "Katıl",
      desc: "GeoGuessrTürkiye'ye katılım rehberi: Discord sunucusu, topluluk kuralları ve sık sorulan sorular. Üyelik açık ve ücretsiz.",
      eyebrow: "Katıl",
      h1: "Aramıza katılmak iki dakika sürer.",
      lead: "Üyelik açık ve ücretsizdir. Tek ihtiyacın bir Discord hesabı; gerisini bu rehber anlatıyor.",
      koordinat: "ÜYELİK: AÇIK · ÜCRET: YOK · SEVİYE ŞARTI: YOK",
      adimEyebrow: "Adım Adım",
      adimH2: "Katılım rehberi",
      adimlar: [
        { ad: "Discord davetine tıkla", p: "Aşağıdaki bağlantı seni doğrudan sunucumuza götürür. Türkiye'den erişimde sorun yaşarsan panik yok: duyurularımız bu sitede de yayınlanır.", btn: "Sunucuya Katıl", btnTip: "discord" },
        { ad: "Profilini at, onaylan", p: "Kuralları onayladıktan sonra GeoGuessr profil linkini #rol-başvuru kanalına at. Ekip profilini kontrol edip sana Verified rolünü verir; böylece sunucudaki tüm kanallar açılır." },
        { ad: "Bildirim rollerini seç", p: "#self-role kanalındaki mesajlara tepki (reaction) bırakarak ilgini çeken bildirimleri aç: turnuvalar, içerik üreticilerinin yayınları ve videoları, mevsimlik lig challenge'ları, parti etkinlikleri ve günlük challenge hatırlatmaları. İngilizce konuşan arkadaşların için English rolü ve english-chat kanalı da burada." },
        { ad: "İlk lobine gir", p: "Duyuru kanallarını takip et, sana uyan etkinliği seç ve lobiye katıl. İlk maçında sıralama beklentisi yok; buradaki herkes bir zamanlar ilk tahminini yaptı.", btn: "Etkinlikleri Gör", btnTip: "etkinlik" },
      ],
      kuralEyebrow: "Kurallar",
      kuralH2: "Topluluk kuralları",
      kuralLead: "Discord sunucumuzda ve tüm etkinliklerimizde geçerli olan düzen. Kısa, net ve herkes için aynı.",
      kurallar: [
        { no: "K.01", b: "Ayrımcılığa yer yok.", p: "Irkçı, cinsiyetçi veya herhangi bir grubu ya da kişiyi hedef alan; ötekileştiren, küçük düşürücü, incitici ve hakaret içeren ifadeler yasaktır." },
        { no: "K.02", b: "Üyeleri rahatsız etme.", p: "Diğer üyeleri rahatsız eden her tür davranış yasaktır." },
        { no: "K.03", b: "Uygunsuz içerik paylaşma.", p: "Müstehcen ve uygunsuz içerik paylaşmak yasaktır." },
        { no: "K.04", b: "Spam yapma.", p: "Mesaj sağanağı, zincir mesaj ve tekrarlı içerik yasaktır." },
        { no: "K.05", b: "Kişisel bilgiler izinsiz paylaşılmaz.", p: "Bir üyenin fotoğrafını, ismini, konumunu veya başka bir kişisel bilgisini izin almadan paylaşmak yasaktır." },
        { no: "K.06", b: "Hile yapma.", p: "GeoGuessr'da hile yapmak yasaktır; etkinliklerde harici araç veya dış yardım kullanmak diskalifiye sebebidir." },
        { no: "K.07", b: "Tek hesapla katıl.", p: "Sunucuya birden fazla hesapla girmek yasaktır." },
        { no: "K.08", b: "Seslenilebilir bir kullanıcı adı kullan.", p: "Yalnızca noktalama işaretlerinden veya rastgele karakterlerden oluşan, seslenmeyi zorlaştıran kullanıcı adları kabul edilmez; gerekirse yöneticiler tarafından değiştirilir." },
      ],
      kuralNot: "Bu kurallara uymayanlara, ihlalin ağırlığına göre susturma veya sunucudan uzaklaştırma cezası uygulanır.",
      sssEyebrow: "SSS",
      sssH2: "Sık sorulan sorular",
      sss: [
        { s: "GeoGuessr nedir?", c: <p>Seni dünyanın rastgele bir noktasına bırakan ve sokak görüntüsüne bakarak nerede olduğunu tahmin etmeni isteyen bir keşif oyunu. Tahminin gerçek konuma ne kadar yakınsa o kadar çok puan alırsın. Kulağa basit geliyor ama ustalaşması yıllar alıyor.</p> },
        { s: "Katılmak için iyi bir oyuncu olmam gerekiyor mu?", c: <p>Hayır. Topluluğun yarısı "Bu hangi ülke?" diye sorarak başladı. Etkinliklerin çoğu her seviyeye açık; ayrıca rehberlerimiz tam da bu yüzden var.</p> },
        { s: "GeoGuessr ücretli değil mi? Etkinliklere nasıl katılacağım?", c: <p>GeoGuessr'ın ücretsiz sürümü sınırlıdır; ancak topluluk etkinliklerimizin çoğuna, etkinlik ekibinin açtığı lobi bağlantıları üzerinden katılabilirsin. Detaylar her etkinliğin duyurusunda yazar.</p> },
        { s: "Sunucuya girdim ama kanalların çoğunu göremiyorum?", c: <p>Sunucu, üyeleri doğruladıktan sonra açılır. GeoGuessr profil linkini #rol-başvuru kanalına at; ekip profilini kontrol edip sana Verified rolünü verir ve tüm kanallar görünür olur.</p> },
        { s: "Duyuruları kaçırmamak için ne yapmalıyım?", c: <p>#self-role kanalındaki mesajlara tepki (reaction) bırakarak istediğin bildirimleri açabilirsin: turnuvalar, içerik üreticilerinin yayınları, mevsimlik lig challenge'ları, parti etkinlikleri ve günlük challenge hatırlatmaları. Yalnızca seçtiğin konuların bildirimi gelir.</p> },
        { s: "Turnuvalara nasıl başvururum?", c: <p>Aktif bir turnuva olduğunda <Link to="/etkinlikler">Etkinlikler sayfasında</Link> başvuru formu açılır; Discord kullanıcı adın ve GeoGuessr profil linkinle bir dakikada başvurursun. Sonuçlar ve fikstür Discord'daki turnuva kanalından duyurulur.</p> },
        { s: "Kulüplere nasıl katılırım? Doluysa ne yapmalıyım?", c: <p><Link to="/kulupler">Kulüpler sayfasındaki</Link> bağlantılardan doğrudan katılabilirsin. Kontenjan doluysa aynı sayfadaki başvuru formunu doldur; yer açıldığında Discord üzerinden haber veririz.</p> },
        { s: "Discord'a Türkiye'den erişemiyorum, ne yapmalıyım?", c: <p>Türkiye'den Discord erişiminde zaman zaman sorun yaşanabiliyor. Bu site tam da bu yüzden var: duyurular, takvim ve rehberler her zaman burada yayınlanır.</p> },
        { s: "Hangi modlarda oynuyorsunuz?", c: <p>Üç ana modumuz var: Moving (serbest hareket), No Move (sabit nokta) ve NMPZ (hareket, yakınlaştırma ve etrafa bakma kapalı). Ayrıntılı açıklama <Link to="/">ana sayfadaki sözlükte</Link>.</p> },
        { s: "Nasıl gelişirim? Nereden çalışmalıyım?", c: <p><Link to="/faydali-siteler">Faydalı Siteler sayfasında</Link> topluluğun güvendiği rehber ve araçları topladık; Plonk It ve GeoHints iyi birer başlangıç noktası. Discord'daki rehber kanallarında Türkçe kaynaklar da var; sorularını sormaktan çekinme.</p> },
        { s: "Türkçe bilmeyen arkadaşım katılabilir mi?", c: <p>Elbette. Sunucuda İngilizce konuşanlar için english-chat kanalı var; #self-role kanalından English rolü alması yeterli.</p> },
        { s: "Bu site resmî bir GeoGuessr sitesi mi?", c: <p>Hayır. GeoGuessrTürkiye bağımsız bir oyuncu topluluğudur; GeoGuessr AB ile resmî bir bağı yoktur. Oyunun kendisi için <a href="https://www.geoguessr.com" target="_blank" rel="noopener">geoguessr.com</a> adresini ziyaret edebilirsin.</p> },
      ],
      ctaEyebrow: "İletişim",
      ctaH2: "Sorusu olan, kapıyı çalsın.",
      ctaNot: "E-posta adresimiz henüz hazır değil; basın ve iş birliği talepleri dahil bize şimdilik Discord üzerinden ulaşabilirsin.",
      ctaBtn2: "Discord Sunucusu",
    },
  },

  /* ============================================================== ENGLISH */
  en: {
    nav: {
      linkler: [
        { to: "/hakkimizda", ad: "About" },
        { to: "/etkinlikler", ad: "Events" },
        { to: "/kulupler", ad: "Clubs" },
        { to: "/faydali-siteler", ad: "Useful Sites" },
        { to: "/katil", ad: "Join" },
      ],
      discordAria: "Join our Discord server",
      menuAria: "Toggle menu",
      temaAcik: "Switch to light theme",
      temaKoyu: "Switch to dark theme",
      skip: "Skip to content",
      mnavDiscord: "Join the Discord",
      mnavKoordinat: "36–42°N · 26–45°E · TÜRKİYE",
      markaAria: "GeoGuessrTürkiye home",
    },
    footer: {
      aciklama: "The first and largest Turkish GeoGuessr community. An independent community project with no official ties to GeoGuessr AB.",
      sayfalar: "Pages",
      anaSayfa: "Home",
      topluluk: "Community",
      iletisim: "Contact",
      sss: "Frequently Asked Questions",
      telif: "All rights belong to the community.",
      koordinat: "39.93°N · 32.86°E",
      sevgi: "With love from Türkiye",
      mailYok: "Email address not ready yet",
    },
    varsayilanAciklama: "GeoGuessr Türkiye is the first and largest Turkish GeoGuessr community and one of the largest in the world, bringing Türkiye's players together through tournaments, clubs and Turkish guides. Joining is open and free.",
    home: {
      eyebrow: "Türkiye's GeoGuessr Community",
      h1: [
        { w: "A community that knows" },
        { w: "the world" },
        { w: "inside out.", accent: true },
      ],
      tanitim: "GeoGuessrTürkiye is the first and largest Turkish GeoGuessr community, bringing Türkiye's players together on the same map with tournaments, leagues and guides.",
      ctaDiscord: "Join the Discord",
      ctaTani: "Meet the Community",
      meta: [
        ["LOCATION", "Türkiye · 36–42°N / 26–45°E"],
        ["PLATFORM", "Discord + Web"],
        ["MEMBERSHIP", "Open and free"],
      ],
      canli: "Thousands of guesses are made every second",
      manifesto1a: "Chasing street signs, trees, camera generations and the fine details of Google's coverage: ",
      manifesto1em: "a community growing and improving every single day",
      manifesto1b: ".",
      manifesto2: "Whether you're making your very first guess or competing in the world rankings, there is a place for you here. We welcome every newcomer with the same excitement as day one.",
      faktalar: [
        { n: 81, say: true, l: "Provinces Represented" },
        { n: 1300, say: true, ek: "+", l: "Members" },
        { n: "24/7", l: "Always Active" },
        { n: "∞", l: "Locations" },
      ],
      neEyebrow: "What We Do",
      neH2: "GeoGuessrTürkiye in four headlines",
      neler: [
        { no: "01", baslik: "Tournaments & Leagues", to: "/etkinlikler", p: "From one-night cups to a full league: events where players of every level can compete." },
        { no: "02", baslik: "Guides & Meta", to: "/faydali-siteler", p: "Country recognition, plates and driving-side clues, camera generations, bollards… We fill the gap in Turkish resources." },
        { no: "03", baslik: "Clubs", to: "/kulupler", p: "Our official clubs on GeoGuessr: join, wear the badge and represent Türkiye in club competitions." },
        { no: "04", baslik: "Representation & Collabs", to: "/hakkimizda", p: "We represent Türkiye in international events and host friendlies with other countries' communities." },
      ],
      takvimEyebrow: "Schedule",
      takvimH2: "Event calendar",
      takvimBtn: "Events",
      programTag: "Schedule: In the Works",
      programH3: "A regular weekly schedule is coming soon.",
      programP: "Until the calendar is set, all events are announced on our Discord server. You can browse our past tournaments on the Events page.",
      programBtn1: "Follow Announcements",
      programBtn2: "Past Tournaments",
      sozlukEyebrow: "Glossary",
      sozlukH2: "Three modes, three disciplines",
      sozlukLead: "In GeoGuessr, how you play matters as much as what you know. Our events use three main modes.",
      modlar: [
        { abbr: "MODE 01", ad: "Moving", p: "Free exploration. Drive the roads, collect signs, follow the junctions. Builds patience and road knowledge.", kurallar: [["ok", "MOVEMENT", "FREE"], ["ok", "ZOOM", "FREE"], ["ok", "PANNING", "FREE"]] },
        { abbr: "MODE 02", ad: "No Move", p: "Analysis from a single spot. Vegetation, architecture, the angle of the sun… How much detail can you read in one frame?", kurallar: [["no", "MOVEMENT", "OFF"], ["ok", "ZOOM", "FREE"], ["ok", "PANNING", "FREE"]] },
        { abbr: "MODE 03", ad: "NMPZ", p: "Pure instinct. No moving, no zooming, no panning. Reading a country at a glance is the true measure of mastery.", kurallar: [["no", "MOVEMENT", "OFF"], ["no", "ZOOM", "OFF"], ["no", "PANNING", "OFF"]] },
      ],
      ctaEyebrow: "Join Us",
      ctaH2: "Take your seat for the next round.",
      ctaNot: "Note: Discord access from Türkiye can occasionally be disrupted. Announcements and the event calendar are always published on this site.",
      ctaBtn1: "Discord Server",
      ctaBtn2: "How to Join",
    },
    hakkimizda: {
      title: "About",
      desc: "The story of GeoGuessrTürkiye: how the independent community uniting Türkiye's GeoGuessr players was founded, its principles and its team.",
      eyebrow: "About",
      h1: "The GeoGuessr Türkiye Community.",
      lead: "GeoGuessrTürkiye is the first and largest Turkish GeoGuessr community — and one of the largest GeoGuessr communities in the world. Founded by players to bring Türkiye's GeoGuessr players together, this site is the community's public face and official announcement channel.",
      koordinat: "39.93°N · 32.86°E · ANKARA",
      hikayeEyebrow: "Our Story",
      hikayeH2: "From a few players to a community",
      hikaye: [
        "It all started when a few Turkish GeoGuessr players found each other. Reading countries from street views was a fun hobby, but comparing scores, sharing clues and playing together needed a meeting point. That is how our Discord server was born.",
        "Over time, curiosity turned into structure: tournaments, Turkish guides and balanced Türkiye maps built by the community itself… Today, as the first and largest Turkish GeoGuessr community, we are one of the largest GeoGuessr communities in the world — a home where players of every level meet in the same lobby.",
        "This website exists so that access to the community survives any circumstance. Our announcements, event calendar and guides now live at this address, reachable by everyone.",
      ],
      ilkeEyebrow: "Our Principles",
      ilkeH2: "Four principles that hold us together",
      ilkeler: [
        { no: "01", ad: "Curiosity", p: "From the language on a sign to the silhouette of a mountain: an endless appetite for knowing the world. Learning is the game itself." },
        { no: "02", ad: "Competition", p: "The scoreboard is taken seriously, but even the sharpest rivalry never outruns sportsmanship. Fair play is non-negotiable." },
        { no: "03", ad: "Sharing", p: "Meta knowledge is taught, not hoarded. Every newcomer deserves to ask the questions today's masters once asked." },
        { no: "04", ad: "Respect", p: "Players from different cities, ages and skill levels under one roof. Everyone has a place here." },
      ],
      yolEyebrow: "Our Journey",
      yolH2: "Milestones",
      yolculuk: [
        { tarih: "31.12.2022", etiket: "Founded", ad: "The first meetup", p: "A handful of players came together on Discord with the dream of a Turkish-speaking GeoGuessr server, and GeoGuessrTürkiye was born." },
        { tarih: "2023", etiket: "Tournaments", ad: "Tournaments begin", p: "The first GeoGuessr Türkiye tournaments were held. The format itself became a community tradition as much as the winners." },
        { tarih: "Growth", etiket: "Guides", ad: "Guides and maps", p: "Turkish meta guides were published; balanced Türkiye maps made by community members reached players." },
        { tarih: "2026", etiket: "Live", ad: "geoturkiye.community goes live", p: "The community's permanent, public address is online. Announcements, the calendar and guides now live under one roof." },
      ],
      ekipEyebrow: "Team",
      ekipH2: "Who runs the community?",
      ekipLead: "GeoGuessrTürkiye runs entirely on volunteer effort.",
      ekipKisiler: [
        { ad: "Oğuzhan Sarıgöl", rol: "Moderator", img: "/ekip/oguzhansarigol.png", youtube: "https://www.youtube.com/@oguzhansarigol", instagram: "https://www.instagram.com/oguzhansarigol_" },
        { ad: "Ahmet Yusuf Kartal", rol: "Moderator", img: "/ekip/ahmetyusufkartal.png", youtube: "https://www.youtube.com/@ayusufkartal", instagram: "https://www.instagram.com/a.yusufkartal" },
        { ad: "Fez", rol: "Moderator", img: "/ekip/fez.png", youtube: "https://www.youtube.com/@regularcinemapod", kick: "https://kick.com/butfezz" },
      ],
      ekipCokluBaslik: "Volunteer Staff",
      ekipCokluP: "And many more volunteers keep the server running together, every single day.",
      ctaEyebrow: "Join In",
      ctaH2: "Let's write the next chapter together.",
      ctaBtn1: "Discord Server",
      ctaBtn2: "How to Join",
    },
    etkinlikler: {
      title: "Events",
      desc: "GeoGuessrTürkiye tournaments: past tournaments and preparations for the new season. Announcements on Discord.",
      eyebrow: "Events",
      h1: "New tournaments are on the way.",
      lead: "There is no active tournament right now. So far we have held three GeoGuessr Türkiye tournaments and one offline event; preparations for the next ones are underway.",
      koordinat: "STATUS: UNDER CONSTRUCTION",
      insaTag: "Page Under Construction",
      insaH3: "A new tournament season is in the making.",
      insaP: "This page will be updated once the format and calendar are set. Until then, all announcements are published on our Discord server.",
      insaBtn: "Follow Announcements",
      turnuvaEyebrow: "Registration",
      turnuvaH2: "Open tournaments",
      tKontenjan: "Capacity",
      tBasvurBtn: "Apply",
      tVazgec: "Cancel",
      tDolu: "Registration full",
      tDiscordNot: "Announcements are posted in the tournament channel on our Discord server — stay tuned after applying.",
      fDiscord: "Discord username",
      fDiscordPh: "e.g. geoturkiye",
      fProfil: "GeoGuessr profile link",
      fProfilPh: "https://www.geoguessr.com/user/…",
      fAdSoyad: "Full name (optional)",
      fGonder: "Submit Application",
      fGonderiliyor: "Submitting…",
      fBasari: "Your application has been received! Results and announcements will be shared in the tournament channel on Discord.",
      fHataTekrar: "An application with this Discord username already exists for this tournament.",
      fHataGenel: "Application could not be submitted. The tournament may be closed or full — reach us on Discord.",
      fZorunlu: "Please fill in the required fields.",
      arsivEyebrow: "Archive",
      arsivH2: "Past tournaments",
      tabloBasliklar: ["#", "Tournament", "Date", "Format"],
      gecmis: [
        { no: "01", ad: "GeoGuessr Türkiye Tournament 1", tarih: "05.08.2023", tur: "Online" },
        { no: "02", ad: "GeoGuessr Türkiye Tournament 2", tarih: "02.09.2023", tur: "Online" },
        { no: "03", ad: "GeoGuessr Türkiye Tournament 3", tarih: "Date to be added", tur: "Online" },
        { no: "04", ad: "Offline Tournament", tarih: "Date to be added", tur: "In person" },
      ],
      ctaEyebrow: "Ready?",
      ctaH2: "Don't miss the next one.",
      ctaBtn1: "Discord Server",
      ctaBtn2: "How to Join",
    },
    kulupler: {
      title: "Clubs",
      desc: "GeoGuessrTürkiye clubs on GeoGuessr: join the main club or its sister clubs, wear the badge and represent Türkiye.",
      eyebrow: "Clubs",
      h1: "Our clubs.",
      lead: "Our official clubs on GeoGuessr. Join, wear the badge and be part of the community. The clubs may be full — if there is no room, leave an application below and we'll reach out on Discord when a spot opens.",
      koordinat: "3 CLUBS · ON GEOGUESSR",
      liste: [
        { ad: "GeoGuessr Türkiye", tag: "Main Club", url: "https://www.geoguessr.com/clubs/4d3821c4-6e74-4c41-a5ed-6a12ca38970e", p: "The community's main club. The badge and the community live here; if it's full, apply below." },
        { ad: "GeoGuessr Türkiye 2", tag: "Club 02", url: "https://www.geoguessr.com/clubs/8258105f-5397-400e-983c-29103330ecc7", p: "Second stop for when the main club is full. Same community, same excitement." },
        { ad: "GeoGuessrTürkiye 3", tag: "Club 03", url: "https://www.geoguessr.com/clubs/ae825f43-3377-4a54-9141-3ac4afd624c0", p: "Our third club. There is always room for newcomers." },
      ],
      katilBtn: "Join the Club",
      not: "A GeoGuessr account is required to join. Club capacity is limited; if the main club is full, continue with the next one.",
      basvurBtn: "Apply to a Club",
      formEyebrow: "Application",
      formH2: "Club application",
      formLead: "Apply here when the clubs are full; we reach out on Discord as spots open up.",
      fKulup: "Club",
      fDiscord: "Discord username",
      fDiscordPh: "e.g. geoturkiye",
      fProfil: "GeoGuessr profile link",
      fProfilPh: "https://www.geoguessr.com/user/…",
      fAdSoyad: "Full name (optional)",
      fGonder: "Submit Application",
      fGonderiliyor: "Submitting…",
      fBasari: "Your application has been received! We will contact you on Discord when a spot opens up.",
      fHataTekrar: "An application with this Discord username already exists for this club.",
      fHataGenel: "Application could not be submitted. Please try again later or reach us on Discord.",
      fZorunlu: "Please fill in the required fields.",
    },
    faydali: {
      title: "Useful Sites",
      desc: "The geoguesser's toolkit: Plonk It, GeoHints, Learnable Meta and more. Trusted resources the community actually uses.",
      eyebrow: "Useful Sites",
      h1: "The geoguesser's toolkit.",
      lead: "From learning meta to making maps: trusted external resources the community uses all the time. All in one list.",
      koordinatSon: "RESOURCES · EXTERNAL LINKS",
      siteler: [
        { no: "01", ad: "GeoGuessr", url: "https://www.geoguessr.com", host: "geoguessr.com", p: "The game's official home. First stop for creating an account and starting to play." },
        { no: "02", ad: "Plonk It", url: "https://www.plonkit.net", host: "plonkit.net", p: "The world's most comprehensive meta guide, country by country. The go-to resource for serious improvement." },
        { no: "03", ad: "Learnable Meta", url: "https://learnablemeta.com", host: "learnablemeta.com", p: "An interactive platform that teaches country meta in bite-sized lessons and reinforces it with quizzes." },
        { no: "04", ad: "MagnusGeo Guide (Turkish)", url: "https://geo.magnusmagi.com/tr", host: "geo.magnusmagi.com/tr", p: "A meta guide written in Turkish; perfect for learning country clues in your own language." },
        { no: "05", ad: "GeoHints", url: "https://geohints.com", host: "geohints.com", p: "Poles, bollards, plates, area codes… Compares countries side by side through visual clues." },
        { no: "06", ad: "GeoTips", url: "https://geotips.net", host: "geotips.net", p: "Short region-by-region notes and practical meta tips; ideal for quick revision." },
        { no: "07", ad: "MagnusGeo", url: "https://magnusgeo.magnusmagi.com", host: "magnusgeo.magnusmagi.com", p: "Practice and quiz tools built to test and sharpen your meta knowledge." },
        { no: "08", ad: "Seterra", url: "https://www.seterra.com", host: "seterra.com", p: "Capitals, flags, provinces… Reinforces geography knowledge with gamified exercises." },
        { no: "09", ad: "Map Making App", url: "https://map-making.app", host: "map-making.app", p: "The community's standard tool for building your own GeoGuessr maps." },
        { no: "10", ad: "r/geoguessr", url: "https://www.reddit.com/r/geoguessr/", host: "reddit.com/r/geoguessr", p: "The international GeoGuessr community's forum; news, discussions and tournament announcements." },
      ],
      not: "All links lead to third-party sites. For our Turkish guides, check the guide channels on our Discord server.",
      ctaEyebrow: "Suggestions",
      ctaH2: "Know a site that belongs on this list?",
      ctaBtn1: "Suggest on Discord",
      ctaBtn2: "How to Join",
    },
    katil: {
      title: "Join",
      desc: "How to join GeoGuessrTürkiye: the Discord server, community rules and frequently asked questions. Membership is open and free.",
      eyebrow: "Join",
      h1: "Joining takes two minutes.",
      lead: "Membership is open and free. All you need is a Discord account; this guide covers the rest.",
      koordinat: "MEMBERSHIP: OPEN · COST: NONE · SKILL REQUIREMENT: NONE",
      adimEyebrow: "Step by Step",
      adimH2: "How to join",
      adimlar: [
        { ad: "Click the Discord invite", p: "The link below takes you straight to our server. If you have trouble connecting from Türkiye, don't worry: our announcements are also published on this site.", btn: "Join the Server", btnTip: "discord" },
        { ad: "Post your profile, get verified", p: "After accepting the rules, post your GeoGuessr profile link in the #rol-başvuru channel. The team checks your profile and gives you the Verified role, which unlocks every channel on the server." },
        { ad: "Pick your notification roles", p: "React to the messages in the #self-role channel to opt into what interests you: tournaments, content creators' streams and videos, seasonal league challenges, party events and daily challenge reminders. The English role and the english-chat channel live there too." },
        { ad: "Enter your first lobby", p: "Follow the announcement channels, pick an event that suits you and join the lobby. No ranking expectations in your first match; everyone here once made their first guess too.", btn: "See the Events", btnTip: "etkinlik" },
      ],
      kuralEyebrow: "Rules",
      kuralH2: "Community rules",
      kuralLead: "The order that applies on our Discord server and at every event. Short, clear and the same for everyone.",
      kurallar: [
        { no: "R.01", b: "No discrimination.", p: "Racist, sexist or otherwise discriminatory, demeaning, hurtful or insulting language targeting any group or person is forbidden." },
        { no: "R.02", b: "Don't harass members.", p: "Any behaviour that disturbs other members is forbidden." },
        { no: "R.03", b: "No inappropriate content.", p: "Sharing obscene or inappropriate content is forbidden." },
        { no: "R.04", b: "No spam.", p: "Message floods, chain messages and repetitive content are forbidden." },
        { no: "R.05", b: "Personal info stays private.", p: "Sharing a member's photo, name, location or any other personal information without permission is forbidden." },
        { no: "R.06", b: "No cheating.", p: "Cheating in GeoGuessr is forbidden; using external tools or outside help during events means disqualification." },
        { no: "R.07", b: "One account only.", p: "Joining the server with more than one account is forbidden." },
        { no: "R.08", b: "Use a readable username.", p: "Usernames made only of punctuation or random characters that make addressing you impossible are not accepted; moderators may change them if needed." },
      ],
      kuralNot: "Breaking these rules results in a mute or a ban from the server, depending on the severity of the violation.",
      sssEyebrow: "FAQ",
      sssH2: "Frequently asked questions",
      sss: [
        { s: "What is GeoGuessr?", c: <p>A discovery game that drops you at a random point in the world and asks you to guess where you are from the street view. The closer your guess, the more points you score. Sounds simple, but mastering it takes years.</p> },
        { s: "Do I need to be good to join?", c: <p>No. Half the community started by asking "which country is this?". Most events are open to every level, and our guides exist precisely for this.</p> },
        { s: "Isn't GeoGuessr paid? How do I join events?", c: <p>GeoGuessr's free tier is limited, but you can join most of our community events through lobby links opened by the events team. Details are in each event's announcement.</p> },
        { s: "I joined the server but can't see most channels?", c: <p>The server opens up after members are verified. Post your GeoGuessr profile link in the #rol-başvuru channel; the team checks your profile, gives you the Verified role and every channel becomes visible.</p> },
        { s: "How do I make sure I don't miss announcements?", c: <p>React to the messages in the #self-role channel to opt into the notifications you want: tournaments, content creators' streams, seasonal league challenges, party events and daily challenge reminders. You only get pinged about what you picked.</p> },
        { s: "How do I sign up for tournaments?", c: <p>When a tournament is active, a registration form opens on the <Link to="/etkinlikler">Events page</Link>; it takes a minute with your Discord username and GeoGuessr profile link. Results and fixtures are announced in the tournament channel on Discord.</p> },
        { s: "How do I join the clubs? What if they are full?", c: <p>You can join directly through the links on the <Link to="/kulupler">Clubs page</Link>. If they are full, fill in the application form on the same page and we will reach out on Discord when a spot opens.</p> },
        { s: "I can't reach Discord from Türkiye. What should I do?", c: <p>Discord access from Türkiye can occasionally be disrupted. That is exactly why this site exists: announcements, the calendar and guides are always published here.</p> },
        { s: "Which modes do you play?", c: <p>Three main modes: Moving (free movement), No Move (fixed spot) and NMPZ (no moving, zooming or panning). See the <Link to="/">glossary on the home page</Link> for details.</p> },
        { s: "How do I get better? Where should I study?", c: <p>We collected the community's trusted guides and tools on the <Link to="/faydali-siteler">Useful Sites page</Link>; Plonk It and GeoHints are great starting points. There are Turkish resources in the guide channels on Discord too; don't hesitate to ask questions.</p> },
        { s: "Can my non-Turkish-speaking friend join?", c: <p>Of course. The server has an english-chat channel; grabbing the English role from the #self-role channel is all it takes.</p> },
        { s: "Is this an official GeoGuessr site?", c: <p>No. GeoGuessrTürkiye is an independent player community with no official ties to GeoGuessr AB. For the game itself, visit <a href="https://www.geoguessr.com" target="_blank" rel="noopener">geoguessr.com</a>.</p> },
      ],
      ctaEyebrow: "Contact",
      ctaH2: "Got a question? Knock on our door.",
      ctaNot: "Our email address isn't ready yet; for now, reach us on Discord for everything, including press and partnership requests.",
      ctaBtn2: "Discord Server",
    },
  },
};
